### ISSUE TITLE
crypto.c文件里的logfile应该是linux下用的，win下会编译错误

### ISSUE THREAD

**Issue by phoenixxie0** [Windendless/shadowsocks-libev#15]
In file included from crypto.c:36:0:
crypto.c: In function 'crypto_parse_key':
utils.h:97:30: error: unknown conversion type character 'z' in format [-Werror=format=]
             fprintf(logfile, " %s ERROR: " format "\n", timestr, \
                              ^
utils.h:97:30: note: in definition of macro 'LOGE'
             fprintf(logfile, " %s ERROR: " format "\n", timestr, \
                              ^~~~~~~~~~~~~
utils.h:97:30: error: too many arguments for format [-Werror=format-extra-args]
             fprintf(logfile, " %s ERROR: " format "\n", timestr, \
                              ^
utils.h:97:30: note: in definition of macro 'LOGE'
             fprintf(logfile, " %s ERROR: " format "\n", timestr, \
                              ^~~~~~~~~~~~~
utils.h:97:30: error: unknown conversion type character 'z' in format [-Werror=format=]
             fprintf(logfile, " %s ERROR: " format "\n", timestr, \
                              ^
utils.h:97:30: note: in definition of macro 'LOGE'
             fprintf(logfile, " %s ERROR: " format "\n", timestr, \
                              ^~~~~~~~~~~~~
utils.h:97:30: error: too many arguments for format [-Werror=format-extra-args]
             fprintf(logfile, " %s ERROR: " format "\n", timestr, \
                              ^
utils.h:97:30: note: in definition of macro 'LOGE'
             fprintf(logfile, " %s ERROR: " format "\n", timestr, \
                              ^~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors
make[2]: *** [Makefile:921: libshadowsocks_libev_la-crypto.lo] Error 1

**Comment by Windendless** [comment]
Please try: https://github.com/Windendless/shadowsocks-libev/commit/ce8a679b2e40749b49449d41c049504bd500d3a6

**Comment by phoenixxie0** [comment]
OK了.
