### ISSUE TITLE
服务端跟进SIP007之后，这里希望也能够跟进

### ISSUE THREAD

**Issue by phoenixxie0** [Windendless/shadowsocks-libev#17]
服务端跟进SIP007之后，这里希望也能够跟进。3.0.2添加了SIP007的相关改变，导致3.0.1无法连接。

**Comment by Windendless** [comment]
OK.

**Comment by phoenixxie0** [comment]
mbedtls的编译，win下不建议打开share 因为我们在win下使用主要是静态的，如果动态编译mbedtls，那么会增加一个依赖。这样反而不好，修改一下README.md吧。

**Comment by Windendless** [comment]
README updated:https://github.com/Windendless/shadowsocks-libev/commit/fb9daf6c5ed8e3051084faf365282e6e7698816c

**Comment by phoenixxie0** [comment]
在./configure的时候使用--disables-ssp可以取消libssl-0.dll的依赖。并且一般情况下我们都是在win下用mys2+mingw64来编译，嗯。

**Comment by phoenixxie0** [comment]
上游修复了内存泄露的问题，希望跟进

**Comment by phoenixxie0** [comment]
ev.c:1825:31: warning: 'ev_default_loop_ptr' initialized and declared 'extern'
   EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                               ^~~~~~~~~~~~~~~~~~~
ev.c: In function 'evpipe_write':
ev.c:2462:19: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
           buf.buf = &buf;
                   ^
  CCLD     libev.la
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
make[2]: Leaving directory '/local/src/winshadowsocks/libev'
Making all in src
make[2]: Entering directory '/local/src/winshadowsocks/src'
  CC       libshadowsocks_libev_la-utils.lo
  CC       libshadowsocks_libev_la-jconf.lo
  CC       libshadowsocks_libev_la-json.lo
  CC       libshadowsocks_libev_la-udprelay.lo
utils.c: In function 'ss_align':
utils.c:244:11: error: implicit declaration of function 'posix_memalign' [-Werror=implicit-function-declaration]
     err = posix_memalign(&tmp, sizeof(void *), size);
           ^~~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors
make[2]: *** [Makefile:865: libshadowsocks_libev_la-utils.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/local/src/winshadowsocks/src'
make[1]: *** [Makefile:481: all-recursive] Error 1
make[1]: Leaving directory '/local/src/winshadowsocks'
make: *** [Makefile:390: all] Error 2

**Comment by Windendless** [comment]
Please try:  https://github.com/Windendless/shadowsocks-libev/commit/a7b731ba6afbc9d2b9359dc81601700e78abdd77

**Comment by phoenixxie0** [comment]
编译能够通过，但是运行过程中会自己退出。。表现为，运行后，打开两个网页就会自己杀掉

**Comment by Windendless** [comment]
Please try : https://github.com/Windendless/shadowsocks-libev/commit/ffadfaedd32c14105dec007f127bfba55c30ec09

**Comment by phoenixxie0** [comment]
libsodium更新了，并且上游更新了一些ss-local的东西。希望跟进，谢谢
