### ISSUE TITLE
utils.h 中的#include <syslog.h>导致win下无法通过编译

### ISSUE THREAD

**Issue by phoenixxie0** [Windendless/shadowsocks-libev#18]
utils.h 中的#include <syslog.h>导致win下无法通过编译。退回到 clean up的commit之前就可以正常过编译了，具体应该是
#elif defined(_WIN32)

#define TIME_FORMAT "%Y-%m-%d %H:%M:%S"

#define USE_TTY()

#define USE_SYSLOG(ident)

#define LOGI(format, ...)                                                   \
    do {                                                                    \
        time_t now = time(NULL);                                            \
        char timestr[20];                                                   \
        strftime(timestr, 20, TIME_FORMAT, localtime(&now));                \
        fprintf(stderr, " %s INFO: " format "\n", timestr, ## __VA_ARGS__); \
        fflush(stderr); }                                                   \
    while (0)

#define LOGE(format, ...)                                                    \
    do {                                                                     \
        time_t now = time(NULL);                                             \
        char timestr[20];                                                    \
        strftime(timestr, 20, TIME_FORMAT, localtime(&now));                 \
        fprintf(stderr, " %s ERROR: " format "\n", timestr, ## __VA_ARGS__); \
        fflush(stderr); }                                                    \
    while (0)

#else // not LIB_ONLY
这里的问题。

**Comment by Windendless** [comment]
try https://github.com/Windendless/shadowsocks-libev/commit/805a7d72b50d4f4f8ccfe16bddea0353177b0beb
