### ISSUE TITLE
Build failed, json.c error

### ISSUE THREAD

**Issue by phoenixxie0** [Windendless/shadowsocks-libev#19]
make[2]: Entering directory '/opt/src/shadowsocks-libev/src'
  CC       libshadowsocks_libev_la-json.lo
  CC       libshadowsocks_libev_la-cache.lo
  CC       libshadowsocks_libev_la-acl.lo
json.c: In function 'new_value':
json.c:141:42: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
                   (state, values_size + ((unsigned long) value->u.object.values), 0)) )
                                          ^
cc1.exe: all warnings being treated as errors
make[2]: *** [Makefile:893: libshadowsocks_libev_la-json.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/opt/src/shadowsocks-libev/src'
make[1]: *** [Makefile:483: all-recursive] Error 1
make[1]: Leaving directory '/opt/src/shadowsocks-libev'
make: *** [Makefile:392: all] Error 2

**Comment by Windendless** [comment]
try https://github.com/Windendless/shadowsocks-libev/commit/e3c8d438d5ee75e910b14792513cd3280fd3d85d

**Comment by phoenixxie0** [comment]
Yep. I have alreadly fix it by myself according to [https://github.com/shadowsocks/shadowsocks-libev/commit/fbd34516f057255f520731e13a3b625b12e3f769](url)
